"""apikey model

Revision ID: ddfaa1be93c4
Revises: c4ecdcec0341
Create Date: 2025-10-26 00:47:43.664964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddfaa1be93c4'
down_revision = 'c4ecdcec0341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create api_key table (categories and cards already exist from initial migration)
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_expenses_user_category')
        batch_op.create_index(batch_op.f('ix_expenses_user_category'), ['user_id', 'category'], unique=False)
        batch_op.drop_column('card_id')
        batch_op.drop_column('category_id')

    op.drop_table('cards')
    op.drop_table('api_key')
    op.drop_table('categories')
    # ### end Alembic commands ###
